Configure kubectl:
aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)

Deploy Kubernetes Metrics Server:

Download and unzip the metrics server by running the following command:
wget -O v0.3.6.tar.gz https://codeload.github.com/kubernetes-sigs/metrics-server/tar.gz/v0.3.6 && tar -xzf v0.3.6.tar.gz


Deploy the metrics server to the cluster by running the following command:
kubectl apply -f metrics-server-0.3.6/deploy/1.8+/


kubectl get deployment metrics-server -n kube-system

Verify that the metrics server has been deployed:


kubectl apply -f https://raw.githubusercontent.com/hashicorp/learn-terraform-provision-eks-cluster/main/kubernetes-dashboard-admin.rbac.yaml
